package com.ocp.day19.derby.select;

import java.sql.Connection;  
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.apache.derby.jdbc.ClientDataSource;

public class Select4ClientDataSource2 {
	public static void main(String[] args) throws SQLException, ClassNotFoundException {
		ClientDataSource clientDataSource = new ClientDataSource();
		clientDataSource = new ClientDataSource();
		clientDataSource.setServerName("");
		clientDataSource.setPortNumber(0000);
		clientDataSource.setDatabaseName("");
		clientDataSource.setUser("");
		clientDataSource.setPassword("");		

		// Establish Connection
		Connection connection = clientDataSource.getConnection();
		// Create Statement
		Statement statement = connection.createStatement();
		// MySQL statement for SELECT
		String sql4select = "SELECT s4jwe.badge, s4jwe.name FROM SQL4javaWebEE s4jwe";

		// A table of data representing a database result set, which is usually
		// generated by executing a statement that queries the database.
		ResultSet resultSet = statement.executeQuery(sql4select);
		// Moves the cursor forward one row from its current position
		// while-loop to iterate through the result set
		while (resultSet.next()) {
			int id = resultSet.getInt("badge");
			String name = resultSet.getString("name");
			System.out.printf("| %2d | %-5s |\n", id, name);
		}
	}
}
