package com.ocp.day19.jdbc.select;
/*
	Of this lesson, we used the API of Apache Derby 10.14.2.0 from following link.   
		
		https://db.apache.org/derby/releases/release-10_14_2_0.html
	
	Guideline:
		
		1) Download the .zip of "db-derby-10.14.2.0-bin.zip" and unzip it
		2) Created a folder with naming "database" under the path of db-derby-10.14.2.0-bin
		3)
		4)
		 
	
	
 
*/
import java.sql.Connection; 
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Select4ClientDataSource1 {
	public static void main(String[] args) throws SQLException, ClassNotFoundException {
		
        Class.forName("org.apache.derby.jdbc.ClientDriver");
        String url = "jdbc:derby://localhost:???/???";
        String user = "";
        String password = "";
		
        // Establish Connection
        Connection connection = DriverManager.getConnection(url, user, password);		
		// Create Statement
		Statement statement = connection.createStatement();
		// SELECT statement from MySQL
		String sql4select = "SELECT c.CUSTOMER_ID, c.NAME, c.PHONE, c.EMAIL FROM CUSTOMER c";
		// A table of data representing a database result set, which is usually
		// generated by executing a statement that queries the database.
		ResultSet resultSet = statement.executeQuery(sql4select);
		// Moves the cursor forward one row from its current position
		// while-loop to iterate through the result set
		while (resultSet.next()) {
			int id = resultSet.getInt("CUSTOMER_ID");
			String name = resultSet.getString("NAME");
			String phone = resultSet.getString("PHONE");
            String email = resultSet.getString("EMAIL");
            System.out.printf("| %5d | %-30s | %15s | %-30s |\n", id, name, phone, email);
		}
		
		// Close resources
		resultSet.close();
		statement.close();
		connection.close();
	}
}
